### GET request with a header
GET {{url}}/hotels
Accept: application/json

### GET request with a header by id
GET {{url}}/hotels/10
Accept: application/json

### GET request with a header by id with rooms
GET {{url}}/hotels/2/rooms
Accept: application/json

### POST an arraylist of hotels
POST {{url}}/hotels
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkZhdGltYVwiIiwic3ViIjoiRmF0aW1hIiwiZXhwIjoxNzI4MTM0ODk1LCJyb2xlcyI6ImFkbWluLHVzZXIiLCJ1c2VybmFtZSI6IkZhdGltYSJ9.Yz4o9XruuMI34pvVhFAi0ZLKrZEczPU5oxddD26HOQk

[
  {
    "name": "Ocean View Hotel",
    "address": "123 Beach Avenue, Miami, FL 33139"
  },
  {
    "name": "Mountain Retreat",
    "address": "456 Alpine Road, Aspen, CO 81611"
  },
  {
    "name": "City Center Inn",
    "address": "789 Downtown St, New York, NY 10001"
  },
  {
    "name": "Desert Oasis Resort",
    "address": "321 Sunflower Blvd, Palm Springs, CA 92262"
  },
  {
    "name": "Riverside Lodge",
    "address": "654 Riverbank Drive, Nashville, TN 37201"
  },
  {
    "name": "Lakeside Villa",
    "address": "987 Lakefront Drive, Lake Tahoe, NV 96150"
  },
  {
    "name": "Historic Castle Inn",
    "address": "135 Medieval Lane, Edinburgh, Scotland EH1 2NG"
  },
  {
    "name": "Urban Boutique Hotel",
    "address": "246 Trendy Way, San Francisco, CA 94102"
  },
  {
    "name": "Safari Lodge",
    "address": "369 Wild Animal Rd, Nairobi, Kenya"
  },
  {
    "name": "Grand Palace Hotel",
    "address": "852 Royal Street, Bangkok, Thailand 10200"
  },
  {
    "name": "Cozy Cabin Resort",
    "address": "753 Pine Hill Rd, Gatlinburg, TN 37738"
  },
  {
    "name": "Seaside Escape",
    "address": "159 Ocean Boulevard, Honolulu, HI 96815"
  },
  {
    "name": "Cultural Heritage Hotel",
    "address": "963 Heritage Way, Kyoto, Japan 600-8005"
  },
  {
    "name": "Luxury Sky Hotel",
    "address": "258 Skyline Dr, Dubai, UAE"
  },
  {
    "name": "Winter Wonderland Lodge",
    "address": "357 Snowy Peak Rd, Quebec City, QC G1L 1A1"
  }
]

### UPDATE
PUT  {{url}}/hotels/5

{
   "name": "City Center Inn",
   "address": "789 Downtown St, New York, NY 10001"
}


### DELETE
DELETE {{url}}/hotels/13

